### ISSUE TITLE
Enable testing on old MATLAB releases

### ISSUE THREAD

**Issue by jm9176** [mathworks/MATLAB-support-for-Zarr-files#102]
Tried the following configuration but ran into some dictionary specific errors which @krisfed is currently investigating. Once those issues are fixed, update the workflow file configuration to include the following

```
name: Run Tests

on: push

jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-14]
        matlab-version: ['R2022b','R2024a']
        python-version: ['3.10','3.11']
        exclude:
            - matlab-version: 'R2022b'
              python-version: '3.11'
            - matlab-version: 'R2024a'
              python-version: '3.10'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up MATLAB
      uses: matlab-actions/setup-matlab@v2
      with:
        release: ${{matrix.matlab-version}}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{matrix.python-version}}

```
